spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fashion
    driver-class-name: org.mysql.Driver
    username: root
    password: 1234$
jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
server:
  port: 8080